import tkinter as tk
from tkinter import messagebox
import random

dutch_words = [
    {"word": "hallo", "translation": "hello"},
    {"word": "goedemorgen", "translation": "good morning"},
    {"word": "goedenacht", "translation": "good night"},
    {"word": "goedendag", "translation": "good day"},
    {"word": "eten", "translation": "food"},
    {"word": "water", "translation": "water"},
    {"word": "hond", "translation": "dog"},
    {"word": "kat", "translation": "cat"},
    {"word": "vogel", "translation": "bird"},
    {"word": "huis", "translation": "house"},
    {"word": "auto", "translation": "car"},
    {"word": "fiets", "translation": "bicycle"},
    {"word": "school", "translation": "school"},
    {"word": "boek", "translation": "book"},
    {"word": "tafel", "translation": "table"},
    {"word": "stoel", "translation": "chair"},
    {"word": "pen", "translation": "pen"},
    {"word": "potlood", "translation": "pencil"},
    {"word": "telefoon", "translation": "telephone"},
    {"word": "computer", "translation": "computer"},
    {"word": "televisie", "translation": "television"},
    {"word": "muziek", "translation": "music"},
    {"word": "film", "translation": "movie"},
    {"word": "zomer", "translation": "summer"},
    {"word": "winter", "translation": "winter"},
    {"word": "lente", "translation": "spring"},
    {"word": "herfst", "translation": "autumn"},
    {"word": "maandag", "translation": "Monday"},
    {"word": "dinsdag", "translation": "Tuesday"},
    {"word": "woensdag", "translation": "Wednesday"},
    {"word": "donderdag", "translation": "Thursday"},
    {"word": "vrijdag", "translation": "Friday"},
    {"word": "zaterdag", "translation": "Saturday"},
    {"word": "zondag", "translation": "Sunday"},
    {"word": "jaar", "translation": "year"},
    {"word": "maand", "translation": "month"},
    {"word": "dag", "translation": "day"},
    {"word": "uur", "translation": "hour"},
    {"word": "minuut", "translation": "minute"},
    {"word": "seconde", "translation": "second"},
    {"word": "geld", "translation": "money"},
    {"word": "bank", "translation": "bank"},
    {"word": "sleutel", "translation": "key"},
    {"word": "weg", "translation": "road"},
    {"word": "stad", "translation": "city"},
    {"word": "land", "translation": "country"},
    {"word": "wereld", "translation": "world"},
    {"word": "taal", "translation": "language"},
    {"word": "bedankt", "translation": "thank you"},
    {"word": "graag gedaan", "translation": "you're welcome"},
    {"word": "alstublieft", "translation": "please"},
    {"word": "ja", "translation": "yes"},
    {"word": "nee", "translation": "no"},
    {"word": "eten", "translation": "food"},
    {"word": "drinken", "translation": "drink"},
    {"word": "slapen", "translation": "sleep"},
    {"word": "werken", "translation": "work"},
    {"word": "spelen", "translation": "play"},
    {"word": "lezen", "translation": "read"},
    {"word": "schrijven", "translation": "write"},
    {"word": "lopen", "translation": "walk"},
    {"word": "rennen", "translation": "run"},
    {"word": "zwemmen", "translation": "swim"},
    {"word": "kijken", "translation": "watch"},
    {"word": "luisteren", "translation": "listen"},
    {"word": "zingen", "translation": "sing"},
    {"word": "dansen", "translation": "dance"},
    {"word": "lachen", "translation": "laugh"},
    {"word": "huilen", "translation": "cry"},
    {"word": "liefde", "translation": "love"},
    {"word": "vriend", "translation": "friend"},
    {"word": "familie", "translation": "family"},
    {"word": "moeder", "translation": "mother"},
    {"word": "vader", "translation": "father"},
    {"word": "broer", "translation": "brother"},
    {"word": "zus", "translation": "sister"},
    {"word": "opa", "translation": "grandfather"},
    {"word": "oma", "translation": "grandmother"},
    {"word": "huisdier", "translation": "pet"},
    {"word": "natuur", "translation": "nature"},
    {"word": "bloem", "translation": "flower"},
    {"word": "boom", "translation": "tree"},
    {"word": "bos", "translation": "forest"},
    {"word": "strand", "translation": "beach"},
    {"word": "bergen", "translation": "mountains"},
    {"word": "hemel", "translation": "sky"},
    {"word": "zon", "translation": "sun"},
    {"word": "maan", "translation": "moon"},
    {"word": "ster", "translation": "star"},
    {"word": "regen", "translation": "rain"},
    {"word": "wind", "translation": "wind"},
    {"word": "sneeuw", "translation": "snow"},
    {"word": "warm", "translation": "warm"},
    {"word": "koud", "translation": "cold"},
    {"word": "groot", "translation": "big"},
    {"word": "klein", "translation": "small"},
    {"word": "oud", "translation": "old"},
    {"word": "jong", "translation": "young"},
    {"word": "mooi", "translation": "beautiful"},
    {"word": "lelijk", "translation": "ugly"},
    {"word": "snel", "translation": "fast"},
    {"word": "langzaam", "translation": "slow"},
    {"word": "duur", "translation": "expensive"},
    {"word": "goedkoop", "translation": "cheap"},
    {"word": "dichtbij", "translation": "near"},
    {"word": "ver", "translation": "far"},
    {"word": "binnen", "translation": "inside"},
    {"word": "buiten", "translation": "outside"},
    {"word": "links", "translation": "left"},
    {"word": "rechts", "translation": "right"},
    {"word": "boven", "translation": "above"},
    {"word": "onder", "translation": "below"},
    {"word": "rood", "translation": "red"},
    {"word": "blauw", "translation": "blue"},
    {"word": "groen", "translation": "green"},
    {"word": "geel", "translation": "yellow"},
    {"word": "zwart", "translation": "black"},
    {"word": "wit", "translation": "white"},
    {"word": "bruin", "translation": "brown"},
    {"word": "paars", "translation": "purple"},
    {"word": "oranje", "translation": "orange"},
    {"word": "grappig", "translation": "funny"},
    {"word": "verdrietig", "translation": "sad"},
    {"word": "blij", "translation": "happy"},
    {"word": "moe", "translation": "tired"},
    {"word": "boos", "translation": "angry"},
    {"word": "bang", "translation": "scared"},
    {"word": "ziek", "translation": "sick"},
    {"word": "gezond", "translation": "healthy"},
]
dutch_words += [
    {"word": "de politie", "translation": "police station"},
    {"word": "nadat", "translation": "after"},
    {"word": "de portemonnee", "translation": "wallet / purse"},
    {"word": "gestolen (stelen)", "translation": "stolen"},
    {"word": "aangifte doen", "translation": "report"},
    {"word": "de politieagent", "translation": "police officer"},
    {"word": "via", "translation": "by way of"},
    {"word": "zat (zitten)", "translation": "was sitting"},
    {"word": "het terras", "translation": "terrace"},
    {"word": "zulk", "translation": "such"},
    {"word": "toen", "translation": "when"},
    {"word": "lag (liggen)", "translation": "was / lay"},
    {"word": "overal", "translation": "everywhere"},
    {"word": "gezocht (zoeken)", "translation": "searched"},
    {"word": "nergens", "translation": "nowhere"},
    {"word": "gelegd (leggen)", "translation": "placed"},
    {"word": "had (hebben)", "translation": "had"},
    {"word": "omdat", "translation": "because"},
    {"word": "de rits", "translation": "zip"},
    {"word": "zodat", "translation": "so that"},
    {"word": "het geld", "translation": "money"},
    {"word": "steeds", "translation": "always"},
    {"word": "viel (vallen)", "translation": "fell"},
    {"word": "gehaald (halen)", "translation": "took"},
    {"word": "de dader", "translation": "culprit"},
    {"word": "terwijl", "translation": "while"},
    {"word": "namelijk", "translation": "it so happens"},
    {"word": "slim", "translation": "clever"},
    {"word": "ziet eruit (eruitzien)", "translation": "looks like"},
    {"word": "oei", "translation": "um / oh"},
    {"word": "in ieder geval", "translation": "at any rate"},
    {"word": "het leer", "translation": "leather"},
    {"word": "verder", "translation": "otherwise"},
    {"word": "het rijbewijs", "translation": "driver’s licence"},
    {"word": "de identiteitskaart", "translation": "ID card"},
    {"word": "de bankpas", "translation": "bank card"},
    {"word": "de bankrekening", "translation": "bank account"},
    {"word": "de rekening", "translation": "account"},
    {"word": "blokkeren", "translation": "block"},
    {"word": "onmiddellijk", "translation": "immediately / at once"},
    {"word": "hoewel", "translation": "although"},
    {"word": "handig (onhandig)", "translation": "handy"},
    {"word": "hoezo", "translation": "how come"},
    {"word": "ophalen", "translation": "get"},
    {"word": "vervelend", "translation": "annoying"},
    {"word": "opgeschreven (opschrijven)", "translation": "written down"},
    {"word": "zodra", "translation": "as soon as"},
    {"word": "gevonden (vinden)", "translation": "found"},
    {"word": "nemen contact op (contact opnemen)", "translation": "contact / get in touch"},
    {"word": "de kans", "translation": "chance"},
    {"word": "als", "translation": "if"},
    {"word": "eerlijk", "translation": "honest"},
]
dutch_words += [
    {"word": "het studentenhuis", "translation": "student house"},
    {"word": "de filosofie", "translation": "philosophy"},
    {"word": "de informatietechnologie", "translation": "information technology"},
    {"word": "de technologie", "translation": "technology"},
    {"word": "de wekker", "translation": "alarm clock"},
    {"word": "de schat", "translation": "darling"},
    {"word": "heerlijk", "translation": "wonderful"},
    {"word": "gedroomd (dromen)", "translation": "dreamt"},
    {"word": "tropisch", "translation": "tropical"},
    {"word": "het eiland", "translation": "island"},
    {"word": "vogels (de vogel)", "translation": "birds (bird)"},
    {"word": "helemaal", "translation": "at all"},
    {"word": "wakker", "translation": "awake"},
    {"word": "ben uitgerust (uitgerust zijn)", "translation": "feel well-rested"},
    {"word": "sta op (opstaan)", "translation": "get up"},
    {"word": "douchen", "translation": "shower"},
    {"word": "lekker", "translation": "delicious"},
    {"word": "het ontbijtje (het ontbijt)", "translation": "breakfast"},
    {"word": "tijdens", "translation": "during"},
    {"word": "gewoon", "translation": "ordinary"},
    {"word": "het programma", "translation": "program"},
    {"word": "het college", "translation": "lecture / class"},
    {"word": "de bibliotheek", "translation": "library"},
    {"word": "het tentamen", "translation": "examination"},
    {"word": "de filosofiegeschiedenis", "translation": "history of philosophy"},
    {"word": "de geschiedenis", "translation": "history"},
    {"word": "de bank", "translation": "bank"},
    {"word": "de hypotheek", "translation": "mortgage"},
    {"word": "het avondeten", "translation": "dinner, evening meal"},
    {"word": "de pasta", "translation": "pasta"},
    {"word": "gehaktballetjes (het gehaktballetje)", "translation": "meatballs"},
    {"word": "de tomatensaus", "translation": "tomato sauce"},
    {"word": "de saus", "translation": "sauce"},
    {"word": "wassen", "translation": "wash"},
    {"word": "de storing", "translation": "fault"},
    {"word": "het systeem", "translation": "system"},
    {"word": "ben kwijt (kwijt zijn)", "translation": "lost"},
    {"word": "gegevens (het gegeven)", "translation": "data"},
    {"word": "vreemd", "translation": "strange"},
    {"word": "gekookt (koken)", "translation": "cooked"},
    {"word": "pittig", "translation": "spicy"},
    {"word": "ontzettend", "translation": "really, very"},
    {"word": "de zaal", "translation": "room, hall"},
    {"word": "geluncht (lunchen)", "translation": "had lunch"},
    {"word": "komt terug (terugkomen)", "translation": "coming back"},
    {"word": "mooi", "translation": "great"},
    {"word": "lust (lusten)", "translation": "fancy"},
    {"word": "de thee", "translation": "tea"},
    {"word": "rustig", "translation": "quiet"},
    {"word": "behalve", "translation": "besides"},
    {"word": "vaste (vast)", "translation": "regular"},
    {"word": "het publiek", "translation": "audience"},
    {"word": "niemand", "translation": "nobody"},
    {"word": "het deel", "translation": "part, episode"},
    {"word": "de serie", "translation": "series"},
    {"word": "uitgenodigd (uitnodigen)", "translation": "invited"},
    {"word": "de lieverd", "translation": "sweetheart"},
    {"word": "het studentenhuis", "translation": "student house"},
]
dutch_words += [
    {"word": "de caissère", "translation": "box office assistant"},
    {"word": "reserveren", "translation": "book"},
    {"word": "de voorstelling", "translation": "show / session"},
    {"word": "wat stom", "translation": "how stupid"},
    {"word": "verkeerd", "translation": "wrong"},
    {"word": "gekeken (kijken)", "translation": "looked"},
    {"word": "is al bezig", "translation": "has started"},
    {"word": "het begin", "translation": "beginning"},
    {"word": "gemist (missen)", "translation": "missed"},
    {"word": "draaien", "translation": "are showing"},
    {"word": "de zomerhitte", "translation": "summer heat"},
    {"word": "de zomer", "translation": "summer"},
    {"word": "de hitte", "translation": "heat"},
    {"word": "eerder", "translation": "earlier"},
    {"word": "opgenomen (opnemen)", "translation": "filmed"},
    {"word": "naar een verhaal van", "translation": "based on a story by"},
    {"word": "de natuurdocumentaire", "translation": "nature documentary"},
    {"word": "de documentaire", "translation": "documentary"},
    {"word": "gesproken (spreken)", "translation": "spoken"},
    {"word": "de ondertiteling", "translation": "subtitles"},
    {"word": "ondertiteld (ondertitelen)", "translation": "subtitled"},
    {"word": "bijna", "translation": "almost"},
    {"word": "de rang", "translation": "class"},
]
dutch_words += [
    {"word": "het openbaar vervoer", "translation": "public transport"},
    {"word": "Colombia", "translation": "Columbia"},
    {"word": "ging (gaan)", "translation": "went"},
    {"word": "het vliegtuig", "translation": "aeroplane"},
    {"word": "duurde (duren)", "translation": "took / lasted"},
    {"word": "helaas", "translation": "unfortunately"},
    {"word": "logeren", "translation": "stay"},
    {"word": "pakken (het pak)", "translation": "packets"},
    {"word": "veilig", "translation": "safe"},
    {"word": "de trein", "translation": "train"},
    {"word": "de tas", "translation": "bag"},
    {"word": "geweldig", "translation": "fantastic"},
    {"word": "vertrekt (vertrekken)", "translation": "leaves"},
    {"word": "de koffer", "translation": "suitcase"},
    {"word": "dragen", "translation": "carry"},
    {"word": "het grapje", "translation": "joke"},
    {"word": "het raampje (raam)", "translation": "window"},
    {"word": "net als", "translation": "like"},
    {"word": "vroeger", "translation": "in the old days"},
    {"word": "lekker", "translation": "nicely"},
    {"word": "buiten", "translation": "outside"},
    {"word": "reis (reizen)", "translation": "travel"},
    {"word": "het spoor", "translation": "platform"},
    {"word": "achter de rug", "translation": "behind (you)"},
    {"word": "pony’s (de pony)", "translation": "ponies"},
    {"word": "de wei", "translation": "field"},
    {"word": "net", "translation": "like"},
    {"word": "de shetlandpony", "translation": "Shetland pony"},
    {"word": "het landschap", "translation": "landscape"},
    {"word": "anders", "translation": "different"},
    {"word": "plat", "translation": "flat"},
    {"word": "de berg", "translation": "mountain"},
    {"word": "gewend", "translation": "used to"},
    {"word": "opletten", "translation": "pay attention"},
    {"word": "zo meteen", "translation": "very soon"},
    {"word": "het natuurgebied", "translation": "nature reserve"},
    {"word": "de natuur", "translation": "nature"},
    {"word": "het gebied", "translation": "area"},
    {"word": "echt", "translation": "real"},
    {"word": "de lucht", "translation": "sky"},
    {"word": "schilderijen (het schilderij)", "translation": "paintings"},
    {"word": "het stukje (het stuk)", "translation": "piece"},
    {"word": "de molen", "translation": "windmill"},
    {"word": "broodjes (het broodje)", "translation": "bread rolls"},
    {"word": "onderweg", "translation": "on the way"},
    {"word": "de kaas", "translation": "cheese"},
    {"word": "moe", "translation": "tired"},
    {"word": "welterusten", "translation": "sleep well"},
    {"word": "goede reis", "translation": "have a good trip"},
    {"word": "maak wakker (wakker maken)", "translation": "wake you up"},
]
dutch_words += [
    {"word": "de sportschool", "translation": "sports club"},
    {"word": "de school", "translation": "school"},
    {"word": "zich inschrijven", "translation": "enrol, to register"},
    {"word": "mensen (de mens)", "translation": "people (person)"},
    {"word": "in de rij staan", "translation": "queue (up)"},
    {"word": "het lid", "translation": "member"},
    {"word": "het abonnement", "translation": "subscription"},
    {"word": "het verschil", "translation": "difference"},
    {"word": "elke (elk)", "translation": "each"},
    {"word": "opzeggen", "translation": "cancel"},
    {"word": "het bedrag", "translation": "amount"},
    {"word": "beide", "translation": "both"},
    {"word": "onbeperkt", "translation": "unlimited"},
    {"word": "sporten", "translation": "play sports"},
    {"word": "speciale (speciaal)", "translation": "special"},
    {"word": "de aanbieding", "translation": "offer"},
    {"word": "het procent", "translation": "per cent"},
    {"word": "de korting", "translation": "discount"},
    {"word": "gratis", "translation": "free"},
    {"word": "zeker", "translation": "sure, certain"},
    {"word": "de conditie", "translation": "physical condition, fitness"},
    {"word": "verbeteren", "translation": "improve"},
    {"word": "spieren (de spier)", "translation": "muscles"},
    {"word": "versterken", "translation": "strengthen"},
    {"word": "het gewicht", "translation": "weight"},
    {"word": "verliezen", "translation": "lose"},
    {"word": "doelen (het doel)", "translation": "goals, targets"},
    {"word": "nogal", "translation": "quite, rather"},
    {"word": "bent van plan (van plan zijn)", "translation": "intend"},
    {"word": "trouwen", "translation": "marry"},
    {"word": "de liefde", "translation": "love"},
    {"word": "het leven", "translation": "life"},
    {"word": "fitte (fit)", "translation": "healthy"},
    {"word": "aantrekkelijke (aantrekkelijk)", "translation": "attractive"},
    {"word": "de man", "translation": "man"},
    {"word": "de krachttraining", "translation": "weight training"},
    {"word": "de kracht", "translation": "strength, power"},
    {"word": "de training", "translation": "training"},
    {"word": "waarschijnlijk", "translation": "probably"},
    {"word": "de cardio", "translation": "cardio fitness"},
    {"word": "de groepsles", "translation": "group lesson"},
    {"word": "de groep", "translation": "group"},
    {"word": "kijk mee (meekijken)", "translation": "watch"},
    {"word": "het rooster", "translation": "schedule"},
    {"word": "bieden aan (aanbieden)", "translation": "offer"},
    {"word": "virtuele (virtueel)", "translation": "virtual"},
    {"word": "veranderen", "translation": "change"},
    {"word": "de manier", "translation": "way, manner"},
    {"word": "op die manier", "translation": "in that way"},
    {"word": "regelmatig", "translation": "regularly"},
    {"word": "sturen", "translation": "send"},
    {"word": "de nieuwsbrief", "translation": "newsletter"},
    {"word": "het nieuws", "translation": "news"},
    {"word": "de brief", "translation": "letter"},
    {"word": "klinkt (klinken)", "translation": "sound"},
    {"word": "de sportkleren", "translation": "sports clothes"},
    {"word": "de kleren", "translation": "clothes"},
    {"word": "gaat in (ingaan)", "translation": "becomes effective"},
    {"word": "het buikspierkwartier", "translation": "abs workout"},
    {"word": "meteen", "translation": "straightaway"},
    {"word": "meedoen", "translation": "join in"},
    {"word": "aandoen", "translation": "put on"},
    {"word": "maak klaar (klaarmaken)", "translation": "prepare, get ready"},
    {"word": "het pasje", "translation": "card"},
    {"word": "verkopen", "translation": "sell"},
    {"word": "energiedrankjes (het energiedrankje)", "translation": "energy drinks"},
    {"word": "de energie", "translation": "energy"},
    {"word": "het drankje", "translation": "drink"},
    {"word": "de automaat", "translation": "vending machine"},
    {"word": "het muntgeld", "translation": "cash"},
    {"word": "het saldo", "translation": "balance"},
    {"word": "laden", "translation": "charge"},
    {"word": "veel plezier", "translation": "have fun"},
    {"word": "het plezier", "translation": "fun"},
    {"word": "de spierpijn", "translation": "muscular pain"},
    {"word": "bang", "translation": "afraid"},
]
dutch_words += [
    {"word": "bezoekt (bezoeken)", "translation": "is visiting"},
    {"word": "kom binnen (binnenkomen)", "translation": "come in"},
    {"word": "de kerk", "translation": "church"},
    {"word": "zei (zeggen)", "translation": "said"},
    {"word": "kon (kunnen)", "translation": "could"},
    {"word": "missen", "translation": "go wrong / fail"},
    {"word": "gelukkig", "translation": "fortunately"},
    {"word": "meegenomen (meenemen)", "translation": "brought"},
    {"word": "moest (moeten)", "translation": "had to"},
    {"word": "de auto", "translation": "car"},
    {"word": "brengen", "translation": "take"},
    {"word": "lekker", "translation": "well"},
    {"word": "groeten", "translation": "greetings"},
    {"word": "Doe haar de groeten terug", "translation": "Give her our regards"},
    {"word": "vroeg", "translation": "early"},
    {"word": "verontschuldigen", "translation": "apologize"},
    {"word": "doe uit (uitdoen)", "translation": "take off"},
    {"word": "het weer", "translation": "weather"},
    {"word": "hè", "translation": "isn’t it"},
    {"word": "Zeg dat wel!", "translation": "You can say that again!"},
    {"word": "koud", "translation": "cold"},
    {"word": "nat", "translation": "wet"},
    {"word": "ben verkouden", "translation": "have a cold"},
    {"word": "ik ben toe aan (toe zijn aan)", "translation": "I need"},
    {"word": "hebben aan (aanhebben)", "translation": "have on"},
    {"word": "de verwarming", "translation": "heating"},
    {"word": "belachelijk", "translation": "ridiculous"},
    {"word": "geloof (geloven)", "translation": "believe"},
    {"word": "schijnt (schijnen)", "translation": "seems"},
    {"word": "kom … verder (verderkomen)", "translation": "come in"},
    {"word": "ah", "translation": "ah"},
    {"word": "lekker warm", "translation": "nice and warm"},
    {"word": "warm", "translation": "warm"},
    {"word": "de doos", "translation": "box"},
    {"word": "bonbons (de bonbon)", "translation": "chocolates"},
    {"word": "de bos", "translation": "bunch"},
    {"word": "bloemen (de bloem)", "translation": "flowers"},
    {"word": "de vaas", "translation": "vase"},
    {"word": "zetten", "translation": "put"},
    {"word": "snijd (snijden)", "translation": "cut"},
    {"word": "schuin", "translation": "at an angle"},
    {"word": "afsnijden", "translation": "cut off"},
    {"word": "houden van", "translation": "like / fond of / love"},
    {"word": "dieren (het dier)", "translation": "animals"},
    {"word": "de hond", "translation": "dog"},
    {"word": "katten (de kat)", "translation": "cats"},
    {"word": "vissen (de vis)", "translation": "fish"},
    {"word": "jawel", "translation": "oh yes"},
    {"word": "meestal", "translation": "usually"},
    {"word": "gezellig", "translation": "pleasant / sociable"},
    {"word": "hadden (hebben)", "translation": "used to have / had"},
    {"word": "het ongeluk", "translation": "accident"},
    {"word": "hebben gehad (hebben)", "translation": "had"},
    {"word": "onder de auto gekomen (onder de auto komen)", "translation": "was run over"},
    {"word": "hebben verdriet gehad om (verdriet hebben om)", "translation": "grieved for"},
    {"word": "het verdriet", "translation": "grief"},
    {"word": "de dood", "translation": "death"},
    {"word": "volgens mij", "translation": "in my opinion"},
    {"word": "volgens", "translation": "according to"},
    {"word": "de gezondheid", "translation": "health"},
    {"word": "lachen", "translation": "laugh"},
    {"word": "gezond", "translation": "healthy"},
    {"word": "kom mee (meekomen)", "translation": "come"},
    {"word": "de schuur", "translation": "shed"},
    {"word": "twee weken geleden", "translation": "two weeks ago"},
    {"word": "jongen (het jong)", "translation": "litter"},
    {"word": "gekregen (krijgen)", "translation": "had"},
    {"word": "iemand", "translation": "someone"},
    {"word": "laatste (laatst)", "translation": "last"},
]
dutch_words += [
    {"word": "het station", "translation": "train station"},
    {"word": "bekend", "translation": "known"},
    {"word": "de voorbijganger", "translation": "passer-by"},
    {"word": "de buschauffeur", "translation": "bus driver"},
    {"word": "de bus", "translation": "bus"},
    {"word": "de chauffeur", "translation": "driver"},
    {"word": "lopen", "translation": "walk"},
    {"word": "te", "translation": "too"},
    {"word": "zeker", "translation": "certainly"},
    {"word": "vanaf", "translation": "from"},
    {"word": "de tram", "translation": "tram"},
    {"word": "de lijn", "translation": "line (number)"},
    {"word": "hebt geluk (geluk hebben)", "translation": "are lucky"},
    {"word": "komt aan (aankomen)", "translation": "is arriving"},
    {"word": "net", "translation": "just"},
    {"word": "direct", "translation": "straightaway"},
    {"word": "instappen", "translation": "get in"},
    {"word": "het stuk", "translation": "short distance"},
    {"word": "de ingang", "translation": "entrance"},
    {"word": "over … steken (oversteken)", "translation": "cross"},
    {"word": "de balie", "translation": "information desk"},
    {"word": "de hal", "translation": "hall"},
    {"word": "de portier", "translation": "porter"},
    {"word": "boven", "translation": "upstairs"},
    {"word": "ga op (opgaan)", "translation": "go up"},
    {"word": "de trap", "translation": "stairs"},
    {"word": "rechtdoor", "translation": "straight ahead"},
    {"word": "tot", "translation": "as far as"},
    {"word": "herkent (herkennen)", "translation": "recognize"},
    {"word": "linksaf", "translation": "to the left"},
    {"word": "het eind", "translation": "end"},
    {"word": "rechts", "translation": "on the right"},
    {"word": "neemt mee (meenemen)", "translation": "take"},
    {"word": "de plattegrond", "translation": "map"},
    {"word": "toiletten (het toilet)", "translation": "toilets"},
    {"word": "beneden", "translation": "downstairs"},
    {"word": "de hoek", "translation": "corner"},
    {"word": "ga … om (omgaan)", "translation": "turn"},
    {"word": "ga … af (afgaan)", "translation": "go down"},
    {"word": "uitlopen", "translation": "walk down"},
    {"word": "vanzelf", "translation": "as a matter of course"},
    {"word": "bordjes (het bordje)", "translation": "signs"},
    {"word": "volgen", "translation": "follow"},
    {"word": "makkelijker ((ge)makkelijk)", "translation": "easier"},
]
dutch_words += [
    {"word": "de buurvrouw", "translation": "neighbour (f)"},
    {"word": "leven", "translation": "live"},
    {"word": "hoera", "translation": "hooray"},
    {"word": "van harte gefeliciteerd", "translation": "happy birthday"},
    {"word": "feliciteren met", "translation": "congratulate on"},
    {"word": "het cadeautje (het cadeau)", "translation": "present"},
    {"word": "het kaartje", "translation": "ticket"},
    {"word": "het festival", "translation": "festival"},
    {"word": "hoop (hopen)", "translation": "hope"},
    {"word": "dat", "translation": "that"},
    {"word": "nog geen", "translation": "not yet"},
    {"word": "Cubaanse", "translation": "Cuban"},
    {"word": "de muziek", "translation": "music"},
    {"word": "ben gek op (gek zijn op)", "translation": "am crazy about"},
    {"word": "me herinneren (zich herinneren)", "translation": "remember"},
    {"word": "de keer", "translation": "time"},
    {"word": "verteld (vertellen)", "translation": "told"},
    {"word": "de taart", "translation": "cake"},
    {"word": "je weet de weg (de weg weten)", "translation": "you know the way"},
    {"word": "doe open", "translation": "open"},
    {"word": "de deur", "translation": "door"},
    {"word": "eerst", "translation": "first"},
    {"word": "gezien (zien)", "translation": "seen"},
    {"word": "het bedrijf", "translation": "company"},
    {"word": "de accountant", "translation": "accountant"},
    {"word": "vergis ik me (zich vergissen)", "translation": "am I mistaken"},
    {"word": "het kantoor", "translation": "office"},
    {"word": "eigen", "translation": "own"},
    {"word": "de baas", "translation": "boss"},
    {"word": "druk", "translation": "busy"},
    {"word": "de tijd", "translation": "time"},
    {"word": "verveel me (zich vervelen)", "translation": "am bored"},
    {"word": "nooit", "translation": "never"},
    {"word": "het buitenland", "translation": "abroad"},
    {"word": "hoor (horen)", "translation": "hear"},
    {"word": "Duits", "translation": "German"},
    {"word": "het accent", "translation": "accent"},
    {"word": "dat klopt", "translation": "that’s right"},
    {"word": "sinds kort", "translation": "recently"},
    {"word": "het bevalt me", "translation": "I enjoy it"},
    {"word": "studeer (studeren)", "translation": "study"},
    {"word": "de student", "translation": "student"},
    {"word": "de logopedie", "translation": "speech therapy"},
    {"word": "naast", "translation": "besides"},
    {"word": "het bijbaantje", "translation": "job on the side / part-time job"},
    {"word": "de studie", "translation": "study"},
    {"word": "iedere (ieder)", "translation": "each / every"},
    {"word": "de bioscoop", "translation": "cinema"},
    {"word": "interesseer je (zich interesseren)", "translation": "are you interested"},
    {"word": "gewoon", "translation": "just"},
    {"word": "begrijp (begrijpen)", "translation": "understand"},
    {"word": "snel", "translation": "fast"},
    {"word": "de hobby", "translation": "hobby"},
    {"word": "niet echt", "translation": "not really"},
    {"word": "de sport", "translation": "sport"},
    {"word": "zwemmen", "translation": "swimming"},
    {"word": "wandelen", "translation": "walking / hiking"},
    {"word": "wat toevallig", "translation": "what a coincidence"},
    {"word": "de Wandelbeurs", "translation": "Walking Fair"},
    {"word": "bereid me voor op (zich voorbereiden op)", "translation": "am getting ready for"},
    {"word": "de wandelreis", "translation": "walking tour"},
    {"word": "de reis", "translation": "trip"},
    {"word": "Chili", "translation": "Chile"},
    {"word": "de informatie", "translation": "information"},
    {"word": "interessant", "translation": "interesting"},
    {"word": "opschrijven", "translation": "write down"},
    {"word": "onthouden", "translation": "remember"},
    {"word": "langzamer (langzaam)", "translation": "more slowly"},
    {"word": "de pen", "translation": "pen"},
    {"word": "het papier", "translation": "paper"},
    {"word": "praten", "translation": "speak"},
]
dutch_words += [
    {"word": "de fiets", "translation": "bike / bicycle"},
    {"word": "de fietsenmaker", "translation": "cycle repairman"},
    {"word": "inderdaad", "translation": "indeed"},
    {"word": "duidelijk", "translation": "clear"},
    {"word": "lijkt (lijken)", "translation": "seems / appears"},
    {"word": "total loss", "translation": "a write-off"},
    {"word": "gebeurd (gebeuren)", "translation": "happened"},
    {"word": "gevallen (vallen)", "translation": "fallen"},
    {"word": "regende (regenen)", "translation": "was raining"},
    {"word": "glad", "translation": "slippery"},
    {"word": "fietste weg (wegfietsen)", "translation": "cycled away"},
    {"word": "fietsen", "translation": "cycle"},
    {"word": "de praktijk", "translation": "practice"},
    {"word": "wilde (willen)", "translation": "wanted"},
    {"word": "rechts afslaan", "translation": "turn right"},
    {"word": "gleed weg (wegglijden)", "translation": "slipped"},
    {"word": "mankeerde (mankeren)", "translation": "was wrong"},
    {"word": "zelf", "translation": "myself"},
    {"word": "een slag in het wiel", "translation": "the wheel is crooked"},
    {"word": "het wiel", "translation": "wheel"},
    {"word": "het stuur", "translation": "handlebars"},
    {"word": "het zadel", "translation": "seat"},
    {"word": "staan", "translation": "are (stand)"},
    {"word": "scheef", "translation": "crooked"},
    {"word": "het ding", "translation": "thing"},
    {"word": "zo’n", "translation": "such a"},
    {"word": "de bagagedrager", "translation": "carrier"},
    {"word": "afgebroken (afbreken)", "translation": "broken"},
    {"word": "bedoelt (bedoelen)", "translation": "mean"},
    {"word": "de trapper", "translation": "pedal"},
    {"word": "kapot", "translation": "broken"},
    {"word": "banden (de band)", "translation": "tyres"},
    {"word": "verstaan (verstaan)", "translation": "heard"},
    {"word": "logisch", "translation": "logical"},
    {"word": "helemaal", "translation": "completely"},
    {"word": "rijdt (rijden)", "translation": "goes (rides)"},
    {"word": "remmen (de rem)", "translation": "brakes"},
    {"word": "deden (doen)", "translation": "worked"},
    {"word": "controleren", "translation": "check"},
    {"word": "in orde maken", "translation": "fix"},
    {"word": "tiptop in orde", "translation": "in tip-top condition"},
    {"word": "leer (leren)", "translation": "learn"},
    {"word": "uitdrukkingen (de uitdrukking)", "translation": "expression"},
    {"word": "klaar", "translation": "ready"},
    {"word": "Koningsdag", "translation": "King’s Day"},
    {"word": "de feestdag", "translation": "public holiday"},
    {"word": "het feest", "translation": "party / celebration"},
    {"word": "betekent (betekenen)", "translation": "means"},
    {"word": "gesloten (sluiten)", "translation": "closed"},
    {"word": "het einde", "translation": "end"},
    {"word": "ophalen", "translation": "collect"},
]
dutch_words += [
    {"word": "meneer", "translation": "Mr"},
    {"word": "de huisarts", "translation": "doctor / GP"},
    {"word": "de dokter", "translation": "doctor"},
    {"word": "wat is er aan de hand?", "translation": "what’s wrong?"},
    {"word": "zoals", "translation": "as"},
    {"word": "zit ik onder de bultjes", "translation": "I’m covered in lumps / a rash"},
    {"word": "bultjes (de bult)", "translation": "lumps"},
    {"word": "armen (de arm)", "translation": "arms"},
    {"word": "benen (het been)", "translation": "legs"},
    {"word": "de buik", "translation": "stomach"},
    {"word": "de rug", "translation": "back"},
    {"word": "het gezicht", "translation": "face"},
    {"word": "jeuken", "translation": "itch"},
    {"word": "verschrikkelijk", "translation": "terrible"},
    {"word": "van alles", "translation": "everything"},
    {"word": "geprobeerd (proberen)", "translation": "tried"},
    {"word": "geholpen (helpen)", "translation": "helped"},
    {"word": "begonnen (beginnen)", "translation": "begun"},
    {"word": "gisteravond", "translation": "last night"},
    {"word": "gedaan (doen)", "translation": "done"},
    {"word": "overdag", "translation": "during the day"},
    {"word": "gewerkt (werken)", "translation": "worked"},
    {"word": "klanten (de klant)", "translation": "clients"},
    {"word": "bekeken (bekijken)", "translation": "looked at"},
    {"word": "de voetbalvereniging", "translation": "football club"},
    {"word": "geweest (zijn)", "translation": "been"},
    {"word": "het wedstrijdje (de wedstrijd)", "translation": "match"},
    {"word": "gespeeld (spelen)", "translation": "played"},
    {"word": "daarna", "translation": "after that"},
    {"word": "gedronken (drinken)", "translation": "drunk"},
    {"word": "bijzonders (bijzonder)", "translation": "special"},
    {"word": "gegeten (eten)", "translation": "eaten"},
    {"word": "afgelopen", "translation": "past / last few"},
    {"word": "vergeten (vergeten)", "translation": "forgotten"},
    {"word": "denken", "translation": "think"},
    {"word": "o ja", "translation": "oh yes"},
    {"word": "rijp", "translation": "ripe"},
    {"word": "emmers (de emmer)", "translation": "buckets"},
    {"word": "vol", "translation": "full"},
    {"word": "vorig", "translation": "last"},
    {"word": "klachten (de klacht)", "translation": "complaints"},
    {"word": "lijkt op (lijken op)", "translation": "looks like"},
    {"word": "allergische (allergisch)", "translation": "allergic"},
    {"word": "de reactie", "translation": "reaction"},
    {"word": "geef mee (meegeven)", "translation": "give"},
    {"word": "de zalf", "translation": "ointment"},
    {"word": "tegen", "translation": "against"},
    {"word": "de jeuk", "translation": "itch"},
    {"word": "anders", "translation": "otherwise"},
    {"word": "krabt (krabben)", "translation": "scratch"},
    {"word": "de huid", "translation": "skin"},
    {"word": "kapot", "translation": "open"},
    {"word": "sterkte", "translation": "good luck"},
]
dutch_words += [
    {"word": "de makelaar", "translation": "real estate agent"},
    {"word": "de woonruimte", "translation": "accommodation / somewhere to live"},
    {"word": "de stad", "translation": "city / town"},
    {"word": "mezelf", "translation": "myself"},
    {"word": "de vriend", "translation": "(boy)friend"},
    {"word": "samenwonen", "translation": "live together"},
    {"word": "bepaald", "translation": "certain"},
    {"word": "de woning", "translation": "house"},
    {"word": "de tuin", "translation": "garden"},
    {"word": "de bovenwoning", "translation": "upstairs flat"},
    {"word": "het appartement", "translation": "apartment"},
    {"word": "mogelijkheden (de mogelijkheid)", "translation": "possibilities / options"},
    {"word": "zie (zien)", "translation": "see"},
    {"word": "het formulier", "translation": "form"},
    {"word": "maximale (maximaal)", "translation": "maximum"},
    {"word": "de huurprijs", "translation": "rent"},
    {"word": "huren", "translation": "rent"},
    {"word": "laten zien", "translation": "show"},
    {"word": "de computer", "translation": "computer"},
    {"word": "derde", "translation": "third"},
    {"word": "de verdieping", "translation": "floor / storey"},
    {"word": "oude (oud)", "translation": "old"},
    {"word": "de buurt", "translation": "neighbourhood"},
    {"word": "ver", "translation": "far"},
    {"word": "het centrum", "translation": "city centre"},
    {"word": "dicht bij", "translation": "close to"},
    {"word": "het park", "translation": "park"},
    {"word": "de woonkamer", "translation": "living room"},
    {"word": "de vierkante meter", "translation": "square metres"},
    {"word": "vierkante (vierkant)", "translation": "square"},
    {"word": "de meter", "translation": "metre"},
    {"word": "open", "translation": "open"},
    {"word": "de keuken", "translation": "kitchen"},
    {"word": "ruime (ruim)", "translation": "spacious"},
    {"word": "slaapkamers (de slaapkamer)", "translation": "bedroom"},
    {"word": "het balkon", "translation": "balcony"},
    {"word": "het westen", "translation": "west"},
    {"word": "de gang", "translation": "passage(way)"},
    {"word": "de wc", "translation": "toilet"},
    {"word": "eenvoudige (eenvoudig)", "translation": "simple"},
    {"word": "de badkamer", "translation": "bathroom"},
    {"word": "de douche", "translation": "shower"},
    {"word": "hoeven", "translation": "need"},
    {"word": "het bad", "translation": "bath"},
    {"word": "gebruiken", "translation": "use"},
    {"word": "geschikte (geschikt)", "translation": "suitable"},
    {"word": "huizen (het huis)", "translation": "houses"},
    {"word": "te huur", "translation": "to let"},
    {"word": "huur (huren)", "translation": "rent"},
    {"word": "het huisje (het huis)", "translation": "house"},
    {"word": "want", "translation": "because"},
    {"word": "verhuren", "translation": "to let out"},
    {"word": "gemeubileerd", "translation": "furnished"},
    {"word": "kasten (de kast)", "translation": "cupboards"},
    {"word": "bedden (het bed)", "translation": "beds"},
    {"word": "stoelen (de stoel)", "translation": "chairs"},
    {"word": "het bureau", "translation": "desk"},
    {"word": "de bank", "translation": "sofa / couch"},
    {"word": "het voordeel", "translation": "advantage"},
    {"word": "niets", "translation": "nothing"},
    {"word": "zonnige (zonnig)", "translation": "sunny"},
    {"word": "de kamer", "translation": "living room"},
    {"word": "benedenwoning", "translation": "ground-floor flat"},
    {"word": "dat lijkt me fantastisch", "translation": "that sounds great"},
    {"word": "waar", "translation": "true"},
    {"word": "overleggen", "translation": "discuss"},
    {"word": "bel (bellen)", "translation": "phone"},
    {"word": "zo snel mogelijk", "translation": "as soon as possible"},
    {"word": "nieuwe (nieuw)", "translation": "new"},
]
dutch_words += [
    {"word": "de kledingzaak", "translation": "clothes shop"},
    {"word": "de kleding", "translation": "clothes"},
    {"word": "de zaak", "translation": "shop / store"},
    {"word": "om", "translation": "(in order) to"},
    {"word": "de broek", "translation": "trousers"},
    {"word": "kopen", "translation": "buy"},
    {"word": "de verkoopster", "translation": "saleswoman"},
    {"word": "jullie (object)", "translation": "you"},
    {"word": "helpen", "translation": "help"},
    {"word": "het meisje", "translation": "girl"},
    {"word": "de jongen", "translation": "boy"},
    {"word": "zoek (zoeken)", "translation": "am looking"},
    {"word": "de spijkerbroek", "translation": "jeans"},
    {"word": "de maat", "translation": "size"},
    {"word": "normaal", "translation": "usually"},
    {"word": "soms", "translation": "sometimes"},
    {"word": "groter (groot)", "translation": "larger"},
    {"word": "de kleur", "translation": "colour"},
    {"word": "wat voor", "translation": "what kind of"},
    {"word": "het model", "translation": "style"},
    {"word": "lichte (licht)", "translation": "light"},
    {"word": "laag", "translation": "low"},
    {"word": "verschillende (verschillend)", "translation": "different"},
    {"word": "merken (het merk)", "translation": "brand"},
    {"word": "probeert (proberen)", "translation": "try on"},
    {"word": "ze", "translation": "them"},
    {"word": "allebei", "translation": "both"},
    {"word": "maar even", "translation": "just"},
    {"word": "ergens", "translation": "somewhere"},
    {"word": "passen", "translation": "try on"},
    {"word": "paskamers (de paskamer)", "translation": "changing rooms"},
    {"word": "zitten", "translation": "fit"},
    {"word": "beter (goed)", "translation": "better"},
    {"word": "dan", "translation": "than"},
    {"word": "die", "translation": "that"},
    {"word": "hem", "translation": "it"},
    {"word": "wijd", "translation": "wide"},
    {"word": "kleinere (klein)", "translation": "smaller"},
    {"word": "het spijt me", "translation": "I’m sorry"},
    {"word": "kleinste (klein)", "translation": "smallest"},
    {"word": "dit", "translation": "this"},
    {"word": "eventueel", "translation": "if necessary"},
    {"word": "ruilen", "translation": "exchange"},
    {"word": "binnen", "translation": "within"},
    {"word": "de bon", "translation": "receipt"},
    {"word": "T-shirts (het T-shirt)", "translation": "T-shirts"},
    {"word": "liggen", "translation": "are (lie)"},
    {"word": "allerlei", "translation": "all kinds of"},
    {"word": "wit", "translation": "white"},
    {"word": "zwart", "translation": "black"},
    {"word": "roze", "translation": "pink"},
    {"word": "groen", "translation": "green"},
    {"word": "blauw", "translation": "blue"},
    {"word": "zo", "translation": "so"},
    {"word": "beslissen", "translation": "decide"},
    {"word": "staat me het best (staan)", "translation": "suits me best"},
    {"word": "het best (goed)", "translation": "best"},
    {"word": "pinnen", "translation": "pay by debit card"},
]
dutch_words += [
    {"word": "de vriendin", "translation": "(girl)friend"},
    {"word": "het restaurant", "translation": "restaurant"},
    {"word": "de serveerster", "translation": "waitress"},
    {"word": "de tafel", "translation": "table"},
    {"word": "ons", "translation": "us"},
    {"word": "bij", "translation": "at"},
    {"word": "het raam", "translation": "window"},
    {"word": "gaan zitten", "translation": "sit down"},
    {"word": "de menukaart", "translation": "menu"},
    {"word": "alvast", "translation": "in the meantime"},
    {"word": "te", "translation": "to"},
    {"word": "het mineraalwater", "translation": "mineral water"},
    {"word": "ik heb dorst", "translation": "I’m thirsty"},
    {"word": "de dorst", "translation": "thirst"},
    {"word": "mij", "translation": "me"},
    {"word": "alleen", "translation": "only / just"},
    {"word": "het hoofdgerecht", "translation": "main course"},
    {"word": "ik heb honger", "translation": "I’m hungry"},
    {"word": "de honger", "translation": "hunger"},
    {"word": "het voorgerecht", "translation": "starter"},
    {"word": "misschien", "translation": "perhaps"},
    {"word": "het nagerecht", "translation": "dessert"},
    {"word": "de mosterdsoep", "translation": "mustard soup"},
    {"word": "de mosterd", "translation": "mustard"},
    {"word": "de soep", "translation": "soup"},
    {"word": "erg", "translation": "very"},
    {"word": "als", "translation": "as"},
    {"word": "de biefstuk", "translation": "steak"},
    {"word": "frietjes (het frietje)", "translation": "chips"},
    {"word": "eh", "translation": "um"},
    {"word": "de salade", "translation": "salad"},
    {"word": "de kip", "translation": "chicken"},
    {"word": "de rijst", "translation": "rice"},
    {"word": "o nee", "translation": "oh no"},
    {"word": "geen", "translation": "no"},
    {"word": "het vlees", "translation": "meat"},
    {"word": "toch", "translation": "after all"},
    {"word": "vegetarische (vegetarisch)", "translation": "vegetarian"},
    {"word": "de dagschotel", "translation": "today’s special"},
    {"word": "kiezen", "translation": "choose"},
    {"word": "eet smakelijk", "translation": "bon appetit"},
    {"word": "het mes", "translation": "knife"},
    {"word": "de vork", "translation": "fork"},
    {"word": "momentje (het moment)", "translation": "one moment"},
    {"word": "de lepel", "translation": "spoon"},
    {"word": "halen", "translation": "fetch"},
    {"word": "beetje", "translation": "a little"},
    {"word": "moeilijk", "translation": "difficult"},
    {"word": "het gaat wel", "translation": "it’s okay"},
    {"word": "de soort", "translation": "kind"},
    {"word": "de paella", "translation": "paella"},
    {"word": "houd (houden) van", "translation": "like"},
    {"word": "de mosselen", "translation": "mussels"},
    {"word": "proef (proeven)", "translation": "try"},
    {"word": "wat", "translation": "a little, a bit"},
    {"word": "een beetje", "translation": "a bit"},
    {"word": "vet", "translation": "greasy / rich"},
    {"word": "het toetje", "translation": "dessert"},
    {"word": "het ijs", "translation": "icecream"},
    {"word": "vruchten (de vrucht)", "translation": "fruit"},
    {"word": "de chocola", "translation": "chocolate"},
    {"word": "de slagroom", "translation": "whipped cream"},
    {"word": "zonder", "translation": "without"},
    {"word": "alleen", "translation": "only"},
    {"word": "de cappuccino", "translation": "cappuccino"},
    {"word": "laat de rest maar zitten", "translation": "that’s fine / keep the change"},
    {"word": "laten", "translation": "leave"},
    {"word": "dank u", "translation": "thank you"},
    {"word": "de avond", "translation": "evening"},
]
dutch_words += [
    {"word": "boodschappen doen", "translation": "go shopping"},
    {"word": "de markt", "translation": "market"},
    {"word": "de groenteboer", "translation": "greengrocer"},
    {"word": "er", "translation": "there"},
    {"word": "wie is er aan de beurt?", "translation": "who’s next?"},
    {"word": "de beurt", "translation": "turn"},
    {"word": "alsjeblieft", "translation": "please"},
    {"word": "kleine (klein)", "translation": "small"},
    {"word": "de courgette", "translation": "courgette"},
    {"word": "gele (geel)", "translation": "yellow"},
    {"word": "paprika’s (de paprika)", "translation": "bell peppers, sweet peppers"},
    {"word": "mooie (mooi)", "translation": "nice"},
    {"word": "tomaten (de tomaat)", "translation": "tomatoes"},
    {"word": "altijd", "translation": "always"},
    {"word": "sorry", "translation": "sorry"},
    {"word": "(na)tuurlijk", "translation": "of course"},
    {"word": "anders nog iets?", "translation": "anything else?"},
    {"word": "typisch", "translation": "typical"},
    {"word": "het gerecht", "translation": "dish"},
    {"word": "buitenlanders (de buitenlander)", "translation": "foreigners"},
    {"word": "de andijvie", "translation": "endive"},
    {"word": "de stamppot", "translation": "mashed potato and vegetables"},
    {"word": "spekjes (het spekje)", "translation": "bacon"},
    {"word": "vaak", "translation": "often"},
    {"word": "heerlijk", "translation": "delicious"},
    {"word": "goedkope (goedkoop)", "translation": "cheap"},
    {"word": "hoeveel", "translation": "how much"},
    {"word": "heb nodig (nodig hebben)", "translation": "need"},
    {"word": "personen (de persoon)", "translation": "people"},
    {"word": "ongeveer", "translation": "about"},
    {"word": "halve (half)", "translation": "half"},
    {"word": "de kilo", "translation": "kilo"},
    {"word": "aardappels (de aardappel)", "translation": "potatoes"},
    {"word": "de slager", "translation": "butcher"},
    {"word": "was (zijn)", "translation": "was"},
    {"word": "de bloemkool", "translation": "cauliflower"},
    {"word": "het bakje (de bak)", "translation": "punnet"},
    {"word": "champignons (de champignon)", "translation": "mushrooms"},
    {"word": "de peterselie", "translation": "parsley"},
    {"word": "het bosje (de bos)", "translation": "bunch"},
    {"word": "verder nog iets?", "translation": "anything else?"},
    {"word": "boontjes (het boontje)", "translation": "beans"},
    {"word": "verse (vers)", "translation": "fresh"},
    {"word": "de knoflook", "translation": "garlic"},
    {"word": "komkommers (de komkommer)", "translation": "cucumbers"},
    {"word": "de euro", "translation": "euro"},
    {"word": "wel", "translation": "quite"},
    {"word": "genoeg", "translation": "enough"},
    {"word": "waarnaartoe", "translation": "where to"},
    {"word": "de cent", "translation": "cent"},
    {"word": "erbij", "translation": "with it"},
    {"word": "geeft niet", "translation": "doesn’t matter"},
    {"word": "prettig", "translation": "nice"},
    {"word": "het weekend", "translation": "weekend"},
]
dutch_words += [
    {"word": "de straat", "translation": "street"},
    {"word": "vriend", "translation": "friend"},
    {"word": "komt tegen (tegenkomen)", "translation": "meets"},
    {"word": "hé", "translation": "hey"},
    {"word": "geleden", "translation": "ago"},
    {"word": "leuk", "translation": "nice"},
    {"word": "prima", "translation": "wonderful"},
    {"word": "jou", "translation": "you"},
    {"word": "het gaat wel", "translation": "all right"},
    {"word": "problemen (het probleem)", "translation": "problems"},
    {"word": "buren", "translation": "neighbours"},
    {"word": "niet zo", "translation": "not so"},
    {"word": "belangrijk", "translation": "important"},
    {"word": "gaan (gaan)", "translation": "go"},
    {"word": "de week", "translation": "week"},
    {"word": "een paar dagen (dag)", "translation": "a few days"},
    {"word": "Venetië", "translation": "Venice"},
    {"word": "wauw", "translation": "wow"},
    {"word": "prachtig", "translation": "fine / splendid"},
    {"word": "veel", "translation": "many"},
    {"word": "foto’s maken", "translation": "take photos"},
    {"word": "sinds", "translation": "since"},
    {"word": "nieuw", "translation": "new"},
    {"word": "de camera", "translation": "camera"},
    {"word": "romantische (romantisch)", "translation": "romantic"},
    {"word": "de film", "translation": "film"},
    {"word": "na", "translation": "after"},
    {"word": "kijken naar", "translation": "look at"},
    {"word": "direct", "translation": "right now"},
    {"word": "iets", "translation": "something"},
    {"word": "afspreken", "translation": "set a date / make an appointment"},
    {"word": "goed", "translation": "okay"},
    {"word": "thuis", "translation": "at home"},
    {"word": "de afspraak", "translation": "date / appointment"},
    {"word": "maken", "translation": "to make"},
    {"word": "de datum", "translation": "date"},
    {"word": "dat lukt niet (lukken)", "translation": "that doesn’t work"},
    {"word": "dan", "translation": "then"},
    {"word": "kan (kunnen)", "translation": "can"},
    {"word": "blijf (blijven)", "translation": "stay"},
    {"word": "eten", "translation": "eat"},
    {"word": "zal (zullen)", "translation": "will / shall"},
    {"word": "de spaghetti carbonara", "translation": "spaghetti carbonara"},
    {"word": "het plan", "translation": "plan"},
    {"word": "schrijf (schrijven)", "translation": "write"},
    {"word": "de agenda", "translation": "diary"},
    {"word": "hartstikke", "translation": "very / completely"},
    {"word": "hartstikke leuk", "translation": "terrific / fantastic"},
    {"word": "vind ik ook (vinden)", "translation": "I think so too"},
    {"word": "ik moet ervandoor", "translation": "I have to go"},
    {"word": "ervandoor", "translation": "away / off"},
    {"word": "gauw", "translation": "quickly"},
    {"word": "de winkel", "translation": "shop"},
    {"word": "wens (wensen)", "translation": "wish"},
    {"word": "jullie", "translation": "you"},
    {"word": "fijne (fijn)", "translation": "nice / good"},
    {"word": "doe de groeten aan (de groeten doen aan)", "translation": "give my regards to"},
    {"word": "volgende", "translation": "next"},
    {"word": "tot dan", "translation": "until then"},
]
dutch_words += [
    {"word": "viert (vieren)", "translation": "is celebrating"},
    {"word": "de verjaardag", "translation": "birthday"},
    {"word": "het café", "translation": "café / pub"},
    {"word": "samen", "translation": "together"},
    {"word": "gefeliciteerd", "translation": "happy birthday"},
    {"word": "dank je wel", "translation": "thank you"},
    {"word": "dit is", "translation": "this is"},
    {"word": "prettig met je kennis te maken (kennismaken)", "translation": "pleased to meet you"},
    {"word": "kennen (kennen)", "translation": "know (people)"},
    {"word": "elkaar", "translation": "one another"},
    {"word": "drinken", "translation": "drink"},
    {"word": "ik trakteer (trakteren)", "translation": "it’s my treat"},
    {"word": "wil graag (graag willen)", "translation": "would like"},
    {"word": "de cola", "translation": "cola"},
    {"word": "biertje (het bier)", "translation": "beer"},
    {"word": "neem (nemen)", "translation": "have (take)"},
    {"word": "rode (rood)", "translation": "red"},
    {"word": "de wijn", "translation": "wine"},
    {"word": "roep (roepen)", "translation": "call"},
    {"word": "de ober", "translation": "waiter"},
    {"word": "mag (mogen)", "translation": "may"},
    {"word": "bestellen", "translation": "order"},
    {"word": "alstublieft", "translation": "please"},
    {"word": "Franse (Frans)", "translation": "French"},
    {"word": "Spaanse (Spaans)", "translation": "Spanish"},
    {"word": "Zuid-Afrikaanse (Zuid-Afrikaans)", "translation": "South African"},
    {"word": "de", "translation": "the"},
    {"word": "nou", "translation": "well then"},
    {"word": "proost", "translation": "cheers"},
    {"word": "op je verjaardag", "translation": "happy birthday"},
    {"word": "bedankt", "translation": "thanks"},
    {"word": "het poosje", "translation": "short while"},
    {"word": "later (laat)", "translation": "later"},
    {"word": "zullen (zullen)", "translation": "shall"},
    {"word": "nog een keer", "translation": "once more"},
    {"word": "dat is", "translation": "that is"},
    {"word": "goed", "translation": "good"},
    {"word": "het idee", "translation": "idea"},
    {"word": "hetzelfde", "translation": "the same"},
    {"word": "ja, graag", "translation": "yes please"},
    {"word": "dit", "translation": "this"},
    {"word": "het rondje", "translation": "round"},
    {"word": "betaal (betalen)", "translation": "pay"},
    {"word": "geef (geven)", "translation": "give"},
    {"word": "nog maar", "translation": "another"},
    {"word": "het glas", "translation": "glass"},
    {"word": "afrekenen", "translation": "pay / settle the bill"},
    {"word": "alles", "translation": "everything"},
    {"word": "daarom", "translation": "that’s why"},
    {"word": "eerste", "translation": "first"},
    {"word": "tweede", "translation": "second"},
]
dutch_words += [
    {"word": "zitten (zitten)", "translation": "are sitting"},
    {"word": "de kantine", "translation": "canteen"},
    {"word": "deze", "translation": "this"},
    {"word": "de plaats", "translation": "seat / place"},
    {"word": "vrij", "translation": "free"},
    {"word": "ja hoor", "translation": "yes"},
    {"word": "zo", "translation": "okay / right"},
    {"word": "een", "translation": "a(n)"},
    {"word": "lekker", "translation": "nice / delicious"},
    {"word": "het kopje (de kop)", "translation": "cup"},
    {"word": "de koffie", "translation": "coffee"},
    {"word": "al lang", "translation": "for a long time"},
    {"word": "pas", "translation": "only"},
    {"word": "of", "translation": "or"},
    {"word": "welke", "translation": "what"},
    {"word": "eigenlijk", "translation": "actually / really"},
    {"word": "vandaag", "translation": "today"},
    {"word": "donderdag", "translation": "Thursday"},
    {"word": "augustus", "translation": "August"},
    {"word": "morgen", "translation": "tomorrow"},
    {"word": "ik ben jarig (jarig zijn)", "translation": "it’s my birthday"},
    {"word": "wat leuk", "translation": "how nice"},
    {"word": "december", "translation": "December"},
    {"word": "dus", "translation": "so / therefore"},
    {"word": "de winter", "translation": "winter"},
    {"word": "krijg (krijgen)", "translation": "get / receive"},
    {"word": "nog", "translation": "any"},
    {"word": "het bezoek", "translation": "visit / visitors"},
    {"word": "de broer", "translation": "brother"},
    {"word": "jonger (jong)", "translation": "younger"},
    {"word": "maar", "translation": "but"},
    {"word": "wel", "translation": "certainly"},
    {"word": "langer (lang)", "translation": "taller"},
    {"word": "nog meer", "translation": "any more"},
    {"word": "broers (broer)", "translation": "brothers"},
    {"word": "zussen (zus)", "translation": "sisters"},
    {"word": "de zus", "translation": "sister"},
    {"word": "nog", "translation": "as well"},
    {"word": "kijk (kijken)", "translation": "look"},
    {"word": "de foto", "translation": "photo"},
    {"word": "goh", "translation": "oh"},
    {"word": "heel", "translation": "very"},
    {"word": "ander", "translation": "different / other"},
    {"word": "het type", "translation": "type"},
    {"word": "kort", "translation": "short"},
    {"word": "blond", "translation": "blonde"},
    {"word": "het haar", "translation": "hair"},
    {"word": "donker", "translation": "dark"},
    {"word": "de ouders", "translation": "parents"},
    {"word": "komen op bezoek (op bezoek komen)", "translation": "pay a visit"},
    {"word": "op dit moment", "translation": "at the moment"},
    {"word": "Indonesië", "translation": "Indonesia"},
    {"word": "doen (doen)", "translation": "are doing"},
    {"word": "daar", "translation": "there"},
    {"word": "op vakantie", "translation": "on holiday"},
    {"word": "de vakantie", "translation": "holiday"},
    {"word": "de vader", "translation": "father"},
    {"word": "voor", "translation": "for"},
    {"word": "zijn", "translation": "his"},
    {"word": "het werk", "translation": "work"},
    {"word": "het seizoen", "translation": "season"},
    {"word": "wanneer", "translation": "when"},
    {"word": "de zomer", "translation": "summer"},
    {"word": "weet (weten)", "translation": "know"},
    {"word": "niet", "translation": "not"},
    {"word": "vertel (vertellen)", "translation": "tell"},
    {"word": "eens", "translation": "(usually untranslated)"},
    {"word": "over", "translation": "about"},
    {"word": "de familie", "translation": "family"},
    {"word": "dat", "translation": "that"},
    {"word": "wil (willen)", "translation": "want / would like"},
    {"word": "laat", "translation": "late"},
    {"word": "11.00 uur", "translation": "11 o’clock"},
    {"word": "moeten (moeten)", "translation": "should / have to"},
    {"word": "weer", "translation": "again"},
    {"word": "naar", "translation": "to"},
]
dutch_words += [
    {"word": "welkom (in)", "translation": "welcome (to)"},
    {"word": "goedemorgen", "translation": "good morning"},
    {"word": "allemaal", "translation": "everyone"},
    {"word": "de cursus", "translation": "course"},
    {"word": "de", "translation": "the"},
    {"word": "Nederlands", "translation": "Dutch"},
    {"word": "ik", "translation": "I"},
    {"word": "ben (zijn)", "translation": "am"},
    {"word": "en", "translation": "and"},
    {"word": "jullie", "translation": "your (plural)"},
    {"word": "de docent", "translation": "teacher"},
    {"word": "docenten (docent)", "translation": "teachers"},
    {"word": "jullie", "translation": "you (plural)"},
    {"word": "hebben (hebben)", "translation": "have"},
    {"word": "twee", "translation": "two"},
    {"word": "andere", "translation": "other"},
    {"word": "is (zijn)", "translation": "is"},
    {"word": "hij", "translation": "he"},
    {"word": "geeft les (lesgeven)", "translation": "teaches"},
    {"word": "dagen (de dag)", "translation": "days"},
    {"word": "drie", "translation": "three"},
    {"word": "we", "translation": "we"},
    {"word": "beginnen (beginnen)", "translation": "begin / start"},
    {"word": "met", "translation": "with"},
    {"word": "kennismaken", "translation": "get to know"},
    {"word": "wie", "translation": "who"},
    {"word": "ben (zijn)", "translation": "are"},
    {"word": "jij", "translation": "you"},
    {"word": "wat", "translation": "what"},
    {"word": "jouw", "translation": "your (singular)"},
    {"word": "de naam", "translation": "name"},
    {"word": "mijn", "translation": "my"},
    {"word": "dag", "translation": "day"},
    {"word": "je", "translation": "your (singular)"},
    {"word": "de voornaam", "translation": "first name"},
    {"word": "de achternaam", "translation": "surname"},
    {"word": "uit", "translation": "from"},
    {"word": "welk", "translation": "which"},
    {"word": "het land", "translation": "country"},
    {"word": "Engeland", "translation": "England"},
    {"word": "kom (komen)", "translation": "come"},
    {"word": "de buurman", "translation": "neighbour"},
    {"word": "van", "translation": "of"},
    {"word": "hoe", "translation": "how (what)"},
    {"word": "hoe heet jij?", "translation": "what’s your name?"},
    {"word": "heet (heten)", "translation": "is called"},
    {"word": "waar … vandaan", "translation": "where … from"},
    {"word": "waar", "translation": "where"},
    {"word": "China", "translation": "China"},
    {"word": "woon (wonen)", "translation": "live"},
    {"word": "nu", "translation": "now"},
    {"word": "het adres", "translation": "address"},
    {"word": "het nummer", "translation": "number"},
    {"word": "het antwoord", "translation": "answer"},
    {"word": "nee", "translation": "no"},
    {"word": "de postcode", "translation": "postal code"},
    {"word": "u", "translation": "you"},
    {"word": "mevrouw", "translation": "Ms / Mrs"},
    {"word": "woont (wonen)", "translation": "live"},
    {"word": "ook", "translation": "also"},
    {"word": "in", "translation": "in"},
    {"word": "zeg (zeggen)", "translation": "call (say)"},
    {"word": "maar", "translation": "but (just)"},
    {"word": "hoor", "translation": "(for friendliness, usually not translated)"},
    {"word": "ja", "translation": "yes"},
    {"word": "hier", "translation": "here"},
    {"word": "al", "translation": "already"},
    {"word": "twintig", "translation": "twenty"},
    {"word": "het jaar", "translation": "year"},
    {"word": "gaan verder (verdergaan)", "translation": "go on (continue)"},
    {"word": "de les", "translation": "lesson"},
    {"word": "heeft (hebben)", "translation": "has"},
    {"word": "iedereen", "translation": "everyone"},
    {"word": "het boek", "translation": "book"},
    {"word": "het", "translation": "the"},
    {"word": "de tekst", "translation": "text"},
    {"word": "één", "translation": "one"},
    {"word": "op", "translation": "on"},
    {"word": "de bladzijde", "translation": "page"},
    {"word": "acht", "translation": "eight"},
    {"word": "luisteren", "translation": "listen"},
    {"word": "naar", "translation": "to"},
    {"word": "lezen", "translation": "read"},
    {"word": "stoppen (stoppen)", "translation": "stop"},
    {"word": "even", "translation": "for a moment"},
    {"word": "het is", "translation": "it is"},
    {"word": "de pauze", "translation": "break"},
    {"word": "tot straks", "translation": "see you later"},
    {"word": "straks", "translation": "soon / later"},
]


class DutchWordsQuizApp(tk.Tk):
    def __init__(self):
        super().__init__()

        self.title("Dutch Words Quiz App - Questions Left: 0")
        self.geometry("500x400")

        self.score = 0
        self.correct_count = 0
        self.wrong_count = 0

        self.score_label = tk.Label(self, text="Score: 0", font=("Arial", 14))
        self.score_label.pack(pady=10)

        self.question_label = tk.Label(self, text="", font=("Arial", 18))
        self.question_label.pack(pady=20)

        self.option_buttons_frame = tk.Frame(self)
        self.option_buttons_frame.pack()

        self.next_button = tk.Button(self, text="Next Word", command=self.get_next_word)
        self.next_button.pack(pady=10)

        random.shuffle(dutch_words)
        self.total_questions = len(dutch_words)
        self.update_word()

    def update_word(self):
        if dutch_words:
            self.current_word = dutch_words.pop()
            self.question_label.config(text=f"What is the English translation of '{self.current_word['word']}'?")
            self.title("Dutch Words Quiz App - Questions Left: {}".format(len(dutch_words)))

            # Clear previous option buttons
            for widget in self.option_buttons_frame.winfo_children():
                widget.destroy()

            # Create new option buttons
            options = [self.current_word["translation"]]
            for _ in range(3):
                option = random.choice(dutch_words)["translation"]
                while option in options:
                    option = random.choice(dutch_words)["translation"]
                options.append(option)

            random.shuffle(options)
            for option in options:
                self.create_option_button(option)

    def create_option_button(self, option):
        button = tk.Button(self.option_buttons_frame, text=option, font=("Arial", 12), command=lambda: self.check_answer(option))
        button.pack(pady=5, fill=tk.X)

    def check_answer(self, user_translation):
        correct_translation = self.current_word["translation"]

        if user_translation == correct_translation:
            self.score += 1
            self.correct_count += 1
            messagebox.showinfo("Correct", "Your answer is correct!")
        else:
            self.wrong_count += 1
            messagebox.showinfo("Wrong", f"Wrong! The correct answer is '{correct_translation}'.")

        self.update_score()
        self.get_next_word()

    def get_next_word(self):
        if not dutch_words:
            self.show_final_result()
        else:
            self.update_word()

    def update_score(self):
        self.score_label.config(text=f"Score: {self.score} (Correct: {self.correct_count}, Wrong: {self.wrong_count})")

    def show_final_result(self):
        messagebox.showinfo("Quiz Finished", f"Quiz finished!\nYour score: {self.score}\nCorrect: {self.correct_count}\nWrong: {self.wrong_count}")
        self.destroy()

if __name__ == "__main__":
    app = DutchWordsQuizApp()
    app.mainloop()
